# Generated by Django 3.0 on 2019-12-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('imageUri', models.CharField(max_length=200)),
                ('player_jersey_number', models.IntegerField()),
                ('country', models.CharField(default='IN', max_length=40)),
                ('playerHistory', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='team_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logoUri', models.CharField(max_length=200, unique=True)),
                ('club_state', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
