# Generated by Django 3.0 on 2019-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_structure',
            name='playerHistory',
            field=models.TextField(default=''),
        ),
    ]
