# Generated by Django 3.0 on 2019-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_form', '0002_auto_20191222_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(max_length=20)),
                ('second_team', models.CharField(max_length=20)),
                ('match_winner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='points_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
    ]
